Products = {
    ["normal"] = {
        { name = "tosti", price = 2, amount = 50, },
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "kurkakola", price = 2, amount = 50, },
        { name = "twerks_candy", price = 2, amount = 50, },
        { name = "snikkel_candy", price = 2, amount = 50, },
        { name = "sandwich", price = 2, amount = 50, },
        { name = "bandage", price = 100, amount = 50, },
        { name = "lighter", price = 2, amount = 50, },
        { name = "rolling_paper", price = 2, amount = 5000,  },
        { name = "clothing_bag", price = 2, amount = 5000,  },
        { name = "blueberry_elfbar", price = 22, amount = 50,  },
        { name = "bubblegum_elfbar", price = 22, amount = 50,  },
        { name = "cheesecake_elfbar", price = 22, amount = 50,  },
        { name = "cherry_elfbar", price = 22, amount = 50,  },
        { name = "cola_elfbar", price = 22, amount = 50,  },
        { name = "doubleapple_elfbar", price = 22, amount = 50,  },
        { name = "elfbull_elfbar", price = 22, amount = 50,  },
        { name = "grape_elfbar", price = 22, amount = 50,  },
        { name = "greenapple_elfbar", price = 22, amount = 50,  },
        { name = "mango_elfbar", price = 22, amount = 50,  },
        { name = "strawberryice_elfbar", price = 22, amount = 50,  },
        { name = "watermelon_elfbar", price = 22, amount = 50,  },
    },
    ["bar"] = {
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "beer", price = 7, amount = 50, },
        { name = "whiskey", price = 10, amount = 50, },
        { name = "vodka", price = 70000, amount = 50, },
    },
    ["hardware"] = {
        { name = "lockpick", price = 200, amount = 50, },
        { name = "weapon_wrench", price = 250, amount = 250, },
        { name = "weapon_hammer", price = 250, amount = 250, },
        { name = "weapon_bat", price = 500, amount = 50,  requiredGang = { "lostmc" } },  -- Gang only options in stores
        { name = "repairkit", price = 250, amount = 50,  requiredJob = { ["mechanic"] = 0, ["police"] = 0 } },
        { name = "screwdriverset", price = 350, amount = 50, },
        -- { name = "trowel", price = 50, amount = 50, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "firework1", price = 50, amount = 50, },
        { name = "firework2", price = 50, amount = 50, },
        { name = "firework3", price = 50, amount = 50, },
        { name = "firework4", price = 50, amount = 50, },
        { name = "fitbit", price = 400, amount = 150, },
        { name = "cleaningkit", price = 150, amount = 150, },
        { name = "microfibercloth", price = 25, amount = 10, info = {} },
        { name = "blox", price = 50, amount = 10, info = {} },
        { name = "nylonrope", price = 50, amount = 10, info = {} },
        { name = "blowtorch", price = 50, amount = 10, info = {} },
        { name = "laserdrill", price = 50, amount = 10, info = {} },
        { name = "advancedrepairkit", price = 500, amount = 50,  requiredJob = { ["mechanic"] = 0 } },
    },
    ["weedshop"] = {
        { name = "joint", price = 10, amount = 1000, },
        { name = "weapon_poolcue", price = 100, amount = 1000, },
        { name = "weed_nutrition", price = 20, amount = 1000, },
        { name = "empty_weed_bag", price = 2, amount = 1000, },
        { name = "rolling_paper", price = 2, amount = 1000, },
        { name = 'bakingsoda',   price = 50,   amount = 1000, },
        { name = 'emptyvial',    price = 40,   amount = 1000, },
        { name = 'needle',    	price = 60,   amount = 1000, },
    },
    ["gearshop"] = {
        { name = "diving_gear", price = 2500, amount = 10, },
        { name = "jerry_can", price = 200, amount = 50, },
    },
    ["leisureshop"] = {
        { name = "parachute", price = 2500, amount = 10, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "diving_gear", price = 2500, amount = 10, },
    },
    ["weapons"] = {
        { name = "weapon_knife", price = 250, amount = 250, },
        { name = "weapon_bat", price = 250, amount = 250, },
        { name = "weapon_hatchet",price = 250, amount = 250, },
        { name = "weapon_pistol", price = 2500, amount = 5, requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
        { name = "weapon_snspistol", price = 1500, amount = 5, requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
        { name = "weapon_vintagepistol", price = 4000, amount = 5, requiresLicense = {"weapon", "hunting"}, requiresItem = {"weaponlicense", "huntinglicense"} },
        { name = "pistol_ammo", price = 250, amount = 250, },
    },
    ["coffeeplace"] = {
        { name = "coffee", price = 5, amount = 500 },
        { name = "lighter", price = 2, amount = 50 },
    },
    -- ["casino"] = {
    --     { name = 'casinochips', price = 1, amount = 999999 },
    -- },
    ["electronics"] = {
        { name = "phone", price = 850, amount = 50 },
        { name = "radio", price = 250, amount = 50, },
        { name = "screwdriverset", price = 350, amount = 50, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "fitbit", price = 400, amount = 150, },
        { name = "powerbank", price = 30, amount = 50, },
        { name = "tablet", price = 200, amount = 50, },
    },
    ["mechshop"] = {
        { name = "spanner", price = 75, amount = 50 },
        { name = "adjustable_spanner", price = 95, amount = 50, },
        { name = "pliers", price = 50, amount = 50, },
        { name = "buzz_saw", price = 180, amount = 50, },
        { name = "impact_driver", price = 150, amount = 50, },
        { name = "towremote", price = 50, amount = 50, requiredJob = { ["sadot"] = 0 } },
    },
    ["vending"] = {
        { name = "water_bottle", price = 12, amount = 25, },
        { name = "dppepper", price = 12, amount = 25, },
        { name = "sprite", price = 12, amount = 25, },
        { name = "7up", price = 12, amount = 25, },
        { name = "coke", price = 12, amount = 25, },
        { name = "dietdew", price = 12, amount = 25, },
        { name = "mountaindew", price = 12, amount = 25, },
        { name = "cherrycoke", price = 12, amount = 25, },
        { name = "fantaorange", price = 12, amount = 25, },
        { name = "fantagrape", price = 12, amount = 25, },
        { name = "awrootbeer", price = 12, amount = 25, },
        { name = "fantapineapple", price = 12, amount = 25, },
        { name = "twerks_candy", price = 12, amount = 25, },
        { name = "snikkel_candy", price = 12, amount = 25, },
    },
    ["blackmarket"] = {
        { name = "shotgun_ammo", price = 250, amount = 25 },
        { name = "rifle_ammo", price = 250, amount = 25 },
        { name = "snp_ammo", price = 250, amount = 25 },
        { name = "mg_ammo", price = 250, amount = 25 },
        { name = "smg_ammo", price = 250, amount = 25 },
        { name = "weapon_shiv", price = 1000, amount = 20 },
        { name = "weapon_navyrevolver", price = 3000, amount = 5 },
        { name = "weapon_gadgetpistol", price = 4000, amount = 5 },
        { name = "weapon_katana", price = 4000, amount = 20 },
        { name = "weapon_m1911", price = 10000, amount = 5 },
        { name = "weapon_mossberg", price = 18000, amount = 5 },
        { name = "weapon_m110", price = 22000, amount = 5 },
        { name = "weapon_m70", price = 25000, amount = 5 },
        { name = "weapon_carbinerifle_mk2", price = 28000, amount = 5 },
    },
    ["blackmarket2"] = {
        { name = "shotgun_ammo", price = 250, amount = 25 },
        { name = "rifle_ammo", price = 250, amount = 25 },
        { name = "snp_ammo", price = 250, amount = 25 },
        { name = "mg_ammo", price = 250, amount = 25 },
        { name = "smg_ammo", price = 250, amount = 25 },
        { name = "weapon_karambit", price = 1000, amount = 20 },
        { name = "weapon_revolver_mk2", price = 5000, amount = 5 },
        { name = "weapon_doubleaction", price = 6000, amount = 5 },
        { name = "weapon_de", price = 10000, amount = 5 },
        { name = "weapon_smg_mk2", price = 25000, amount = 5 },
        { name = "weapon_hk416", price = 25000, amount = 5 },
        { name = "weapon_ak47", price = 28000, amount = 5 },
        { name = "weapon_gusenberg", price = 48000, amount = 5 },
    },
    ["blackmarket3"] = {
        { name = "shotgun_ammo", price = 250, amount = 25 },
        { name = "rifle_ammo", price = 250, amount = 25 },
        { name = "snp_ammo", price = 250, amount = 25 },
        { name = "mg_ammo", price = 250, amount = 25 },
        { name = "smg_ammo", price = 250, amount = 25 },
        { name = "weapon_sledgehammer", price = 1500, amount = 20 },
        { name = "weapon_ceramicpistol", price = 10000, amount = 5 },
        { name = "weapon_glock18c", price = 12000, amount = 5 },
        { name = "weapon_mp9", price = 28000, amount = 5 },
        { name = "weapon_mp5", price = 28000, amount = 5 },
        { name = "weapon_aks74", price = 28000, amount = 5 },
        { name = "weapon_heavysniper_mk2", price = 40000, amount = 5 },
    },
    ["blackmarket4"] = {
        { name = "shotgun_ammo", price = 250, amount = 25 },
        { name = "rifle_ammo", price = 250, amount = 25 },
        { name = "snp_ammo", price = 250, amount = 25 },
        { name = "mg_ammo", price = 250, amount = 25 },
        { name = "smg_ammo", price = 250, amount = 25 },
        { name = "weapon_dagger", price = 2000, amount = 20 },
        { name = "weapon_fnx45", price = 10000, amount = 5 },
        { name = "weapon_m9", price = 10000, amount = 5 },
        { name = "weapon_pumpshotgun_mk2", price = 18000, amount = 5 },
        { name = "weapon_uzi", price = 25000, amount = 5 },
        { name = "weapon_mac10", price = 25000, amount = 5 },
        { name = "weapon_ak74", price = 28000, amount = 5 },
        { name = "weapon_combatmg_mk2", price = 56000, amount = 5 },
    },
    ["blackmarket5"] = {
        { name = "gruppesechstablet", price = 1200, amount = 25 },
        { name = "remote_bomb", price = 1200, amount = 25 },
        { name = "ignition_bomb", price = 1200, amount = 25 },
        { name = "impact_bomb", price = 1200, amount = 25 },
        { name = "firelighter", price = 1200, amount = 25 },
        -- { name = "sodiumbicarbonate", price = 8, amount = 25 },
        -- { name = "plasticjerrycan", price = 20, amount = 25 },
    },
}
